VERSION="2.20.0"                                                    
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" 

[DOCUMENTATION] 
ORG_NAME="Stellar Gold Token" 
ORG_URL="https://gold.toml.host" 
ORG_LOGO="https://gold.toml.host/logo.png" 

[[CURRENCIES]] 
code="GOLD" 
issuer="GBTEHBQQQ26PEWKAZB777QVYJ4B5G6AP4O4V6IN6UQQDVKMRN5DRGOLD" 
status="live" 
name="Stellar Gold" 
desc="Stellar Gold brings real physical gold into Stellar's blockchain." 
display_decimals=7 
conditions="Every GOLD purchased will be back-up with every gram of real physical gold. The purity of gold is 99.9999% or equivalent with 24 Carat." 
image="https://gold.toml.host/logo.png" 
